# Generated by Django 5.0.4 on 2024-05-06 22:03

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag_smartphone_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartphoneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.smartphone_image_file_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='smartphone',
            name='images',
            field=models.ManyToManyField(to='core.smartphoneimage'),
        ),
    ]
