# Generated by Django 5.0.4 on 2024-05-04 16:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag_smartphone_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.smartphone_image_file_path),
        ),
    ]
